#!/usr/bin/env bash
#
# This script contains functions that help you work with this project.


# Installs a venv and dependencies
python_deps() {
    python3 -m venv ./venv
    source venv/bin/activate
    pip3 install -r requirements.txt
}


# Run if you've added a dep
freeze() {
    pip3 freeze > requirements.txt
}

# Runs the application
main() {
    python3 main.py
}


source run_lib.sh "$@"
